### ISSUE TITLE
error occured and there is no file named domLink.cfg. I have added key in domLink.cfg.example which i got in repo.

### ISSUE THREAD

**Issue by rajeshk28** [vysecurity/DomLink#23]
Traceback (most recent call last):
  File "domLink.py", line 218, in <module>
    main()
  File "domLink.py", line 147, in main
    api_key = args.api if args.api else read_key_from_config()
  File "domLink.py", line 44, in read_key_from_config
    return config.get('API_KEYS', 'whoxy')
  File "/usr/lib/python2.7/ConfigParser.py", line 330, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'API_KEYS'

**Comment by nightowl33** [comment]
hello @rajeshk28 
i had the same problem and  fortunately i was able to solve the problem
you just need to rename the config file to domlink.cfg
