### ISSUE TITLE
Not able to run script

### ISSUE THREAD

**Issue by mograsanjay** [vysecurity/DomLink#28]
! When running the script with  python3 domLink.py  -D starlink.com . Getting below error 
<class 'type'>
Traceback (most recent call last):
  File "domLink.py", line 221, in <module>
    main()
  File "domLink.py", line 150, in main
    api_key = args.api if args.api else read_key_from_config()
  File "domLink.py", line 47, in read_key_from_config
    return config.get('API_KEYS', 'whoxy')
  File "/usr/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'API_KEYS'

**Comment by whoot** [comment]
Its simple:
1. Script needs to be run with Python2
2. You need to set an API key

**Comment by danieltamang806** [comment]
how to set an API?

**Comment by whoot** [comment]
> how to set an API?

It literaly is in the Readme: "Set that API key in a file named domLink.cfg in the same directory."
